### ISSUE TITLE
please release version 5

### ISSUE THREAD

**Issue by hboutemy** [finos/finos-parent-pom#58]
current version 4 has many old plugins, there are many valuable updates in the curent 5-SNAPSHOT

**Comment by maoo** [comment]
Done! It's been quite an adventure, since apparently the latest maven-release-plugin version (3.0.0-M7) breaks integrations with maven-gpg-plugin, see https://github.com/apache/maven-release/pull/125#issuecomment-1302613138 ; had to revert to `3.0.0-M5`.

Added a note on the README.md.

Just hit release on oss.sonatype.org , it may take some time to show up on https://repo1.maven.org/maven2/org/finos/finos/

Thanks for the issue! Quick question: do you use this parent pom? And if so, may I ask for which project? It would be great to list some adopters in the project's README!

**Comment by hboutemy** [comment]
Thank you!
I did not see the issue with gpg, even if I hit it regularly: when it happens, I run one small SNAPSHOT build that does a signature, then it prepare the gpg agent...
FYI, I was waiting for the release on legend-sdlc
